# Collabrative\-based Filtering Movie\_Recommendation

In [1]:
# load libraries

import pandas as pd

In [3]:
ratings = pd.read_csv('ratings.csv')

In [5]:
ratings.head()

   userId  movieId  rating   timestamp
0       1       31     2.5  1260759144
1       1     1029     3.0  1260759179
2       1     1061     3.0  1260759182
3       1     1129     2.0  1260759185
4       1     1172     4.0  1260759205

## Transforming the data for the "Surprise"

In [7]:
ratings = ratings[['userId', 'movieId', 'rating']]

In [9]:
ratings.head()

   userId  movieId  rating
0       1       31     2.5
1       1     1029     3.0
2       1     1061     3.0
3       1     1129     2.0
4       1     1172     4.0

In [11]:
!pip install scikit-surprise

Collecting scikit-surprise
  Downloading scikit_surprise-1.1.4.tar.gz (154 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.4/154.4 kB 6.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: joblib>=1.2.0 in /root/venv/lib/python3.11/site-packages (from scikit-surprise) (1.5.3)
Requirement already satisfied: numpy>=1.19.5 in /root/venv/lib/python3.11/site-packages (from scikit-surprise) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in /root/venv/lib/python3.11/site-packages (from scikit-surprise) (1.11.4)
Building wheels for collected packages: scikit-surprise
  Building wheel for scikit-surprise (pyproject.toml) ... done
  Created wheel for scikit-surprise: filename=scikit_surprise-1.1.4-cp311-cp311-linux_x86_64.whl size=2962673 sha256=b58cc3276d6d0d3f00776e69081881a2ec6fabb53ca8b88c029bca8fe70611f5
  Stored in directory: /root/.cache/pip/wheels/2a/8f/6e/7e2899163e2d85d8266daab4aa1cdabec7a6c56f83c015b5af
Successfully built scikit-surprise
Installing collected packages: scikit-surprise
Successfully installed scikit-surprise-1.1.4

[notice] A new release of pip is available: 24.0 -> 26.1.1
[notice] To update, run: pip install --upgrade pip

In [23]:
# Load the dataset from the ratings to the surprise format.

from surprise import Dataset, Reader

reader = Reader(rating_scale=(1, 5))
dataset = Dataset.load_from_df(ratings, reader)
dataset

## Build training set

In [29]:
trainset = dataset.build_full_trainset()

In [25]:
# Model definition

from surprise import SVD

svd = SVD()

In [31]:
svd.fit(trainset)

In [35]:
svd.predict(1, 1061)

Prediction(uid=1, iid=1061, r_ui=None, est=2.793330163933008, details={'was_impossible': False})

## Validation

In [43]:
actual_data = pd.read_csv('ratings.csv')

In [47]:
from surprise import model_selection

cross_validation = model_selection.cross_validate(svd, data=dataset, measures=['rmse'])

In [49]:
cross_validation

{'test_rmse': array([0.89006008, 0.89725718, 0.8945204 , 0.89616217, 0.90745821]),
 'fit_time': (0.6224677562713623,
  0.6406416893005371,
  0.6312675476074219,
  0.6634969711303711,
  0.6297116279602051),
 'test_time': (0.06694555282592773,
  0.06281161308288574,
  0.061763763427734375,
  0.06018471717834473,
  0.05971407890319824)}

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=7621d118-a50e-437d-b5a6-54ba5cd87c27' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' />
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>